repos:
  - repo: local
    hooks:
      - id: check-format
        name: Check Format
        entry: pnpm exec oxfmt --check
        language: system
        types_or: [ts, json, yaml]
      - id: check-lint
        name: Check Lint
        entry: pnpm exec oxlint
        language: system
        types: [ts]
