repos:
  - repo: local
    hooks:
      - id: check-format
        name: Check Format
        entry: dprint check
        language: system
        types_or: [ts, json, yaml, markdown, svelte]
      - id: check-lint
        name: Check Lint
        entry: npm x oxlint
        language: system
        types: [ts]
